# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Devarsh Ruparelia
tagline:             'Blogs on STEM|Economics|Geopolitics'
description:         'Welcome to my blog.I Ask/Answer a lot on Quora.'
url:                 http://devarsh1997.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Devarsh Ruparelia
  url:               https://twitter.com/devarsh1997
  email:             devarsh.ruparelia@gmail.com

# Custom vars
version:             1.0.0

#Collections 


